operations:
  ACTIVATE_WHATSAPP:
    mapped_operation: activate_whatsapp
  CONFIGURE_PROXY:
    mapped_operation: configure_proxy
  CONFIGURE_VPN:
    mapped_operation: configure_vpn
  CREATE_EMULATOR:
    mapped_operation: create_avd
  start_avd:
    mapped_operation: start_avd
  test5:
    mapped_operation: test5
