configuration/configuration70.yaml:
  record_final_state: true
  final_success_state_code: configuration70
  final_failure_state_code: configuration70
  apps:
    vpn_app:
      package_name: com.wireguard.android
      apk_path: ./apk/wireguard.apk
  steps_order: []
  steps: {}
